### ISSUE TITLE
Check if accessed file succeeded

### ISSUE THREAD

**Issue by POmri** [Belkan/Sudoku#11]
We should throw an error if the access to the file is restricted etc.

**Comment by adargut** [comment]
See this line:
![image](https://user-images.githubusercontent.com/30580593/64922366-37770c00-d7d7-11e9-868c-b4256e747d46.png)

fopen returning null should cover just about everything; for reference:
![image](https://user-images.githubusercontent.com/30580593/64922385-59708e80-d7d7-11e9-8869-86e11a9a2a54.png)

So I think we can close this. Reopen if you're not satisfied.

**Comment by POmri** [comment]
Shouldn't this be checked as well in the loading function? The fact that a file was accessible a second ago, doesn't mean it is accessible right now. I think it should be verified in real time as well, but maybe I'm wrong.
Maybe we should see how others did it.

**Comment by adargut** [comment]
OK, see commit
