### ISSUE TITLE
Is it O.K. to solve an erroneous board?

### ISSUE THREAD

**Issue by adargut** [Belkan/Sudoku#19]
I think I read somewhere that you can't solve [board.txt] if board is erroneous. Maybe I'm wrong?
![image](https://user-images.githubusercontent.com/30580593/64928706-ac246780-d824-11e9-8cb4-178e4b1ac638.png)

**Comment by POmri** [comment]
There was some discussion in the forum, I think the conclusion was this should throw an error (both in edit and in solve).

**Comment by adargut** [comment]
![image](https://user-images.githubusercontent.com/30580593/64942875-eb79a500-d872-11e9-84f6-a233bfa7dfde.png)
Looks like it's OK for edit, need to check for solve

**Comment by adargut** [comment]
Implemented check for conflicting fixed cells before using solve.
