### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by POmri** [Belkan/Sudoku#21]
[1234.txt](https://github.com/Belkan/Sudoku/files/3622711/1234.txt)
This causes segmentation fault when trying to load (save).
The only difference is the added blank lines at the end

**Comment by adargut** [comment]
Fixed, see:
![image](https://user-images.githubusercontent.com/30580593/65078900-b79f9c00-d9a6-11e9-9a9d-84752e2f8f53.png)
