### ISSUE TITLE
Incorrect file path after solving board correctly

### ISSUE THREAD

**Issue by adargut** [Belkan/Sudoku#8]
When you solve a board correctly, then you edit [file.txt] with incorrect file path, it prints "Congrats! You solved the board" although I don't think it's logical? Why should you see the congratulations message twice?

![image](https://user-images.githubusercontent.com/30580593/64910913-376a0400-d724-11e9-88ef-54f6bf8e3c3a.png)

**Comment by POmri** [comment]
The check was being made after each command. I changed it so that it would check only after a command that fills the board in an active way (no redo/undo).
